name: Go CI

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"
  pull_request:
    branches: ["main"]
    paths:
      - "backend/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21" # Or your desired Go version

      - name: Get dependencies
        run: go mod tidy
        working-directory: backend

      - name: Run tests
        run: go test -v ./...
        working-directory: backend

      - name: Format code
        run: |
          if ! go fmt ./...; then
            echo "::error::Go code format issues found."
            exit 1
          fi
        working-directory: backend

      - name: Lint code
        uses: dominikh/staticcheck-action@v1.3.0
        working-directory: backend

      - name: Security audit
        uses: securego/gosec@v2.19.0
        working-directory: backend

      - name: Build
        run: go build -v ./...
        working-directory: backend
